### ISSUE TITLE
README example pipeline does not work - ScriptedPipeline with no arguments causes error.

### ISSUE THREAD

**Issue by kmanning** [manheim/jenkinsfile-pipeline-library#114]
**Describe the bug**
The README pipeline example does not work as-written.

**Example pipeline code**
Provide the content of a Jenkinsfile that imports jenkinsfile-pipeline and can be used to reproduce the problem.  Please provide a minimal code example (ie: please remove/disable all irrelevant plugins/stages, and ensure that the pipeline code is only what is necessary to reproduce the problem.)

**To Reproduce**
1. Create a pipeline using the README example. (See code below)
2. Run the pipeline

**Actual vs Expected behavior**
**Expected:** the pipeline will run successful.
**Actual:** the pipeline errors with 
```
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.kohsuke.groovy.sandbox.impl.GroovyCallSiteSelector.isIllegalCallToSyntheticConstructor(GroovyCallSiteSelector.java:124)
	at org.kohsuke.groovy.sandbox.impl.GroovyCallSiteSelector.findConstructor(GroovyCallSiteSelector.java:51)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedConstructor(Checker.java:201)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.constructorCall(SandboxInvoker.java:21)
	at WorkflowScript.run(WorkflowScript:6)
```

**Relevant version information:**
 - Jenkins pipeline plugin version: 85eb6c2b62de6ba9e314ed7493290b0969ffb190

**Additional context**
Looks like Issue #59 intended to change the `ScriptedPipeline` constructor, but never did.

**Comment by kmanning** [comment]
This is similar to issue #110 and #111
